-- PetFinder production seed
-- Run after supabase-schema.sql in the SQL Editor of project yfbewvcyxlnwxqlvzmic.

begin;

insert into public.ongs (
  id, owner_user_id, name, email, whatsapp, city, neighborhood, address,
  service_area, responsible, founded_at, instagram, approval_status,
  is_verified, description
) values
  ('ong_salvador', 'c7e36dec-21e0-4dee-93fd-21d59adce824', 'Patinhas de Salvador', 'contato@patinhasdesalvador.org', '(71) 99991-1201', 'Salvador', 'Rio Vermelho', 'Rua Conselheiro Pedro Luiz, 214 - Rio Vermelho, Salvador - BA', 'Salvador, especialmente Brotas, Barra, Rio Vermelho, Ondina e Itapua', 'Equipe Patinhas de Salvador', '2019', '@patinhasdesalvador', 'approved', true, 'ONG de resgate e adoção responsável atuando em Salvador no resgate de cães e gatos abandonados.'),
  ('ong_lauro', null, 'Lar Animal Lauro', 'contato@laranimallauro.org', '(71) 99992-2302', 'Lauro de Freitas', 'Vilas do Atlantico', 'Avenida Praia de Itapua, 82 - Vilas do Atlantico, Lauro de Freitas - BA', 'Lauro de Freitas, Itinga, Buraquinho, Portao e Caji', 'Projeto Lar Animal Lauro', '2021', '@laranimallauro', 'approved', true, 'Projeto independente de resgate animal focado em reabilitação e adoção consciente.'),
  ('ong_feira', null, 'Anjos de 4 Patas Feira', 'contato@anjos4patasfeira.org', '(75) 99993-3403', 'Feira de Santana', 'Santa Monica', 'Rua Tupinambas, 517 - Santa Monica, Feira de Santana - BA', 'Feira de Santana, Tomba, Caseb, SIM, Kalilandia e Mangabeira', 'Anjos de 4 Patas Feira', '2018', '@anjos4patasfeira', 'approved', true, 'ONG parceira especializada em resgate de animais de rua e adoção responsável.')
on conflict (id) do update set
  owner_user_id = coalesce(excluded.owner_user_id, public.ongs.owner_user_id),
  name = excluded.name,
  email = excluded.email,
  whatsapp = excluded.whatsapp,
  city = excluded.city,
  neighborhood = excluded.neighborhood,
  address = excluded.address,
  service_area = excluded.service_area,
  responsible = excluded.responsible,
  founded_at = excluded.founded_at,
  instagram = excluded.instagram,
  approval_status = excluded.approval_status,
  is_verified = excluded.is_verified,
  description = excluded.description;

insert into public.pets (
  id, ong_id, name, species, breed, gender, size, age, age_type, city,
  neighborhood, description, image_url, image_gallery, status, tags,
  personality, health_status, vaccinated, castrated, children_compatibility,
  cats_compatibility, dogs_compatibility, energy_level, vaccination_record,
  veterinary_history, special_needs, medications, microchip, weight,
  behavior_profile, adaptation_needs, routine, feeding, ong_notes
) values
  ('pet_salvador_thor', 'ong_salvador', 'Thor', 'dog', 'Vira-lata caramelo', 'macho', 'medio', '3 anos', 'adulto', 'Salvador', 'Brotas', 'Thor foi resgatado em uma area movimentada de Brotas. E alegre, atento e já esta acostumado com passeios curtos.', 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1552053831-71594a27632d?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['brincalhão e leal', 'vacinado', 'medio']::text[], 'brincalhão e leal', 'vacinado', true, true, 'boa', 'precisa de apresentacao gradual', 'boa', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '14 kg', 'brincalhão e leal', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_salvador_mel', 'ong_salvador', 'Mel', 'dog', 'Sem raça definida', 'femea', 'pequeno', '1 ano e 6 meses', 'adulto', 'Salvador', 'Itapua', 'Mel e uma cadelinha doce, resgatada perto de uma escola. Gosta de colo, rotina tranquila e pessoas pacientes.', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['carinhosa e calma', 'histórico de sarna tratada', 'baixo']::text[], 'carinhosa e calma', 'histórico de sarna tratada', true, true, 'boa', 'boa', 'boa', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por histórico de sarna tratada. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '6 kg', 'carinhosa e calma', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_salvador_apolo', 'ong_salvador', 'Apolo', 'dog', 'Mestico de labrador', 'macho', 'grande', '5 anos', 'adulto', 'Salvador', 'Pituba', 'Apolo e tranquilo, anda bem na guia e se adapta melhor a casas com espaço ou tutores que gostem de caminhar.', 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'in_process', array['equilibrado e companheiro', 'precisa de adaptação com outros cães', 'medio']::text[], 'equilibrado e companheiro', 'precisa de adaptação com outros cães', true, true, 'boa', 'não testado', 'seletiva', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por precisa de adaptação com outros cães. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '24 kg', 'equilibrado e companheiro', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_salvador_luna', 'ong_salvador', 'Luna', 'cat', 'Sem raça definida', 'femea', 'pequeno', '2 anos', 'adulto', 'Salvador', 'Barra', 'Luna foi acolhida após aparecer em um condominio. E sociável, usa caixa de areia e gosta de janelas teladas.', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['calma e observadora', 'castrado', 'baixo']::text[], 'calma e observadora', 'castrado', true, true, 'boa', 'boa', 'precisa de adaptação', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '3,5 kg', 'calma e observadora', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_salvador_nina', 'ong_salvador', 'Nina', 'cat', 'Tigrada', 'femea', 'pequeno', '8 meses', 'filhote', 'Salvador', 'Ondina', 'Nina e curiosa, brinca bastante e convive bem com outros gatos. Ideal para família que possa acompanhar sua fase jovem.', 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['curiosa e ativa', 'vacinado', 'alto']::text[], 'curiosa e ativa', 'vacinado', true, false, 'boa', 'boa', 'não testado', 'alto', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '3,5 kg', 'curiosa e ativa', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_salvador_chico', 'ong_salvador', 'Chico', 'cat', 'Branco e cinza', 'macho', 'medio', '6 anos', 'adulto', 'Salvador', 'Federacao', 'Chico e um gato sereno, perfeito para apartamento telado. Procura um lar calmo e previsível.', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'adopted', array['sereno e independente', 'precisa de ambiente calmo', 'baixo']::text[], 'sereno e independente', 'precisa de ambiente calmo', true, true, 'melhor com criancas maiores', 'boa', 'não recomendado', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por precisa de ambiente calmo. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '4,8 kg', 'sereno e independente', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_max', 'ong_lauro', 'Max', 'dog', 'Vira-lata', 'macho', 'medio', '4 anos', 'adulto', 'Lauro de Freitas', 'Centro', 'Max foi resgatado perto de uma avenida e hoje esta confiante. E esperto, obediente e gosta de companhia.', 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['leal e esperto', 'vermifugado', 'medio']::text[], 'leal e esperto', 'vermifugado', true, true, 'boa', 'não testado', 'boa', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '14 kg', 'leal e esperto', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_amora', 'ong_lauro', 'Amora', 'dog', 'Mestica de pinscher', 'femea', 'pequeno', '2 anos', 'adulto', 'Lauro de Freitas', 'Itinga', 'Amora e pequena, alerta e muito apegada quando ganha confianca. Vai bem em apartamento com rotina de passeio.', 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1517849845537-4d257902454a?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'in_process', array['atenta e afetuosa', 'ansiedade por abandono', 'medio']::text[], 'atenta e afetuosa', 'ansiedade por abandono', true, true, 'melhor com criancas maiores', 'boa', 'boa', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por ansiedade por abandono. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '6 kg', 'atenta e afetuosa', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_bento', 'ong_lauro', 'Bento', 'dog', 'Mestico de terrier', 'macho', 'pequeno', '7 meses', 'filhote', 'Lauro de Freitas', 'Vilas do Atlantico', 'Bento e filhote, brincalhão e aprende rápido. Precisa de família disposta a educar com paciencia.', 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['brincalhão e sociável', 'precisa ganhar peso', 'alto']::text[], 'brincalhão e sociável', 'precisa ganhar peso', true, false, 'boa', 'boa', 'boa', 'alto', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por precisa ganhar peso. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '6 kg', 'brincalhão e sociável', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_mia', 'ong_lauro', 'Mia', 'cat', 'Sem raça definida', 'femea', 'pequeno', '1 ano', 'adulto', 'Lauro de Freitas', 'Buraquinho', 'Mia e delicada, usa caixa de areia e prefere ambientes tranquilos. Gosta de carinho quando se sente segura.', 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['doce e discreta', 'muito timido', 'baixo']::text[], 'doce e discreta', 'muito timido', true, true, 'melhor com criancas maiores', 'boa', 'não testado', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por muito timido. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '3,5 kg', 'doce e discreta', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_tom', 'ong_lauro', 'Tom', 'cat', 'Laranja', 'macho', 'medio', '3 anos', 'adulto', 'Lauro de Freitas', 'Portao', 'Tom e comunicativo, gosta de seguir pessoas pela casa e se adapta bem a apartamento telado.', 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['falante e companheiro', 'saudavel', 'medio']::text[], 'falante e companheiro', 'saudavel', true, true, 'boa', 'boa', 'precisa de adaptação', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '4,8 kg', 'falante e companheiro', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_lauro_simba', 'ong_lauro', 'Simba', 'cat', 'Rajado', 'macho', 'medio', '5 anos', 'adulto', 'Lauro de Freitas', 'Caji', 'Simba e calmo e carinhoso. Teve atendimento veterinário recente e esta pronto para um lar com rotina estavel.', 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'in_process', array['calmo e carinhoso', 'infeccao ocular tratada', 'baixo']::text[], 'calmo e carinhoso', 'infeccao ocular tratada', true, true, 'boa', 'seletiva', 'não recomendado', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por infeccao ocular tratada. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '4,8 kg', 'calmo e carinhoso', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_bob', 'ong_feira', 'Bob', 'dog', 'Sem raça definida', 'macho', 'grande', '6 anos', 'adulto', 'Feira de Santana', 'Tomba', 'Bob e forte, manso e gosta de area externa segura. Foi resgatado após circular por uma feira livre.', 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['manso e protetor', 'em tratamento contra doenca do carrapato', 'medio']::text[], 'manso e protetor', 'em tratamento contra doenca do carrapato', true, true, 'boa', 'não testado', 'boa', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por em tratamento contra doenca do carrapato. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '24 kg', 'manso e protetor', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_pandora', 'ong_feira', 'Pandora', 'dog', 'Mestica', 'femea', 'medio', '2 anos', 'adulto', 'Feira de Santana', 'Caseb', 'Pandora e tranquila, obediente e se apega rápido. Procura uma família que valorize rotina e carinho.', 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1560807707-8cc77767d783?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['tranquila e obediente', 'dermatite leve', 'baixo']::text[], 'tranquila e obediente', 'dermatite leve', true, true, 'boa', 'boa', 'boa', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por dermatite leve. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '14 kg', 'tranquila e obediente', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_zeca', 'ong_feira', 'Zeca', 'dog', 'Mestico de beagle', 'macho', 'medio', '9 anos', 'idoso', 'Feira de Santana', 'SIM', 'Zeca e idoso ativo, muito docil e acostumado com pessoas. Precisa de acompanhamento simples de rotina.', 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1558788353-f76d92427f16?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'adopted', array['docil e paciente', 'baixa visão', 'baixo']::text[], 'docil e paciente', 'baixa visão', true, true, 'boa', 'não testado', 'boa', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por baixa visão. Quadro estavel e monitorado.', 'Precisa de rotina tranquila e acompanhamento preventivo por idade.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '14 kg', 'docil e paciente', 'Adaptacao gradual ao novo lar, passeios curtos e rotina previsível nos primeiros dias.', 'Alimenta-se duas vezes ao dia e gosta de passeios leves com supervisao.', 'Ração seca de boa qualidade para cães adultos, ajustada ao porte.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_frida', 'ong_feira', 'Frida', 'cat', 'Escaminha', 'femea', 'pequeno', '2 anos', 'adulto', 'Feira de Santana', 'Serraria Brasil', 'Frida e independente, carinhosa no tempo dela e perfeita para apartamento telado.', 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['independente e carinhosa', 'FIV positivo', 'baixo']::text[], 'independente e carinhosa', 'FIV positivo', true, true, 'melhor com criancas maiores', 'apenas gatos FIV positivos ou lar unico', 'não recomendado', 'baixo', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por FIV positivo. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '3,5 kg', 'independente e carinhosa', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_theo', 'ong_feira', 'Theo', 'cat', 'Preto', 'macho', 'pequeno', '10 meses', 'filhote', 'Feira de Santana', 'Kalilandia', 'Theo e jovem, brincalhão e curioso. Gosta de arranhador, brinquedos e companhia.', 'https://images.unsplash.com/photo-1494256997604-768d1f608cac?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1494256997604-768d1f608cac?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'available', array['brincalhão e curioso', 'vermifugado', 'alto']::text[], 'brincalhão e curioso', 'vermifugado', true, false, 'boa', 'boa', 'precisa de adaptação', 'alto', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Avaliacao veterinaria recente sem alteracoes importantes.', 'Não possui necessidades especiais informadas.', 'Não usa medicação continua.', false, '3,5 kg', 'brincalhão e curioso', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.'),
  ('pet_feira_pipoca', 'ong_feira', 'Pipoca', 'cat', 'Branca e preta', 'femea', 'medio', '4 anos', 'adulto', 'Feira de Santana', 'Mangabeira', 'Pipoca e sociável e muito limpa. Foi acolhida por uma rede de protetores e já esta pronta para adoção.', 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85', array['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200&h=800&auto=format&fit=crop&crop=faces&q=85']::text[], 'in_process', array['sociável e tranquila', 'histórico de esporotricose tratada', 'medio']::text[], 'sociável e tranquila', 'histórico de esporotricose tratada', true, true, 'boa', 'boa', 'não testado', 'medio', 'Vacinas essenciais em dia conforme acompanhamento da ONG.', 'Acompanhamento veterinário recente por histórico de esporotricose tratada. Quadro estavel e monitorado.', 'Pode precisar de cuidado simples de adaptação e revisao veterinaria.', 'Sem medicação fixa. Manter retorno indicado pela ONG se necessario.', false, '4,8 kg', 'sociável e tranquila', 'Adaptacao em ambiente interno, com caixa de areia, telas e espacos de descanso.', 'Alimenta-se duas vezes ao dia, usa caixa de areia e prefere ambiente seguro.', 'Ração seca para gatos, água fresca e ambiente interno telado.', 'A ONG recomenda entrevista, visita responsável e acompanhamento no período de adaptação.')
on conflict (id) do update set
  ong_id = excluded.ong_id,
  name = excluded.name,
  species = excluded.species,
  breed = excluded.breed,
  gender = excluded.gender,
  size = excluded.size,
  age = excluded.age,
  age_type = excluded.age_type,
  city = excluded.city,
  neighborhood = excluded.neighborhood,
  description = excluded.description,
  image_url = excluded.image_url,
  image_gallery = excluded.image_gallery,
  status = excluded.status,
  tags = excluded.tags,
  personality = excluded.personality,
  health_status = excluded.health_status,
  vaccinated = excluded.vaccinated,
  castrated = excluded.castrated,
  children_compatibility = excluded.children_compatibility,
  cats_compatibility = excluded.cats_compatibility,
  dogs_compatibility = excluded.dogs_compatibility,
  energy_level = excluded.energy_level,
  vaccination_record = excluded.vaccination_record,
  veterinary_history = excluded.veterinary_history,
  special_needs = excluded.special_needs,
  medications = excluded.medications,
  microchip = excluded.microchip,
  weight = excluded.weight,
  behavior_profile = excluded.behavior_profile,
  adaptation_needs = excluded.adaptation_needs,
  routine = excluded.routine,
  feeding = excluded.feeding,
  ong_notes = excluded.ong_notes;

commit;

select count(*) as total_ongs from public.ongs
where id in ('ong_salvador', 'ong_lauro', 'ong_feira');

select ong_id, count(*) as total_pets
from public.pets
where ong_id in ('ong_salvador', 'ong_lauro', 'ong_feira')
group by ong_id
order by ong_id;

notify pgrst, 'reload schema';

